spring.application.name=eventday-module

# Update these to match your local Postgres setup
spring.datasource.url=jdbc:postgresql://localhost:5432/EventBridge
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
