spring.application.name=catalog

# ?? PostgreSQL connection ??????????????????
spring.datasource.url=jdbc:postgresql://localhost:5432/eventbridge_db
spring.datasource.username=postgres
spring.datasource.password=Seth@2002#
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? JPA / Hibernate ???????????????????????

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ?? Server ????????????????????????????????

server.port=8080
